

server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_test?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC
    username: eddi
    password: eddi@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      username: eddi
      password: eddi@123
      authentication-database: admin
      database: test-db
      port: 27017
      host: localhost

  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

  cache:
    type: redis

  redis:
    host: 127.0.0.1
    port: 6379

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB